import unicodedata
from dataclasses import dataclass


@dataclass(frozen=True)
class CatalogRoute:
    testcase_id: str
    severity_level: str
    lane: str
    category: str
    priority: str
    primary_department: str
    assigned_pic: str
    notified_departments: list[str]
    suggested_reply: str
    handling_plan: str
    market: str
    sla_minutes: int
    sla_label: str


def normalize_text(value: str) -> str:
    lowered = value.lower().strip()
    normalized = unicodedata.normalize("NFD", lowered)
    without_accents = "".join(character for character in normalized if unicodedata.category(character) != "Mn")
    return without_accents.replace("đ", "d")


def detect_market(message_text: str) -> str:
    haystack = normalize_text(message_text)
    if any(token in haystack for token in ["indonesia", " shopee indonesia", "gip indonesia", " indonesia "]):
        return "ID"
    if any(token in haystack for token in ["malaysia", "gip malaysia", " ringgit", " malaysia "]):
        return "MY"
    if any(token in haystack for token in ["thailand", " thai", "gip thailand", " thailand "]):
        return "TH"
    if any(token in haystack for token in ["philippines", "gip philippines", " peso", " philippines "]):
        return "PH"
    return "PH"


CASE_RULES = [
    {
        "testcase_id": "TC-INV-01",
        "severity_level": "Cấp 2",
        "lane": "Kho - Lệch số lượng tồn kho",
        "category": "Kho - Kiểm tra lệch tồn và kiểm kho thực tế",
        "priority": "High",
        "primary_department": "Kho",
        "assigned_pic": "Kho theo thị trường",
        "notified_departments": ["DVKH", "Kho"],
        "market": "PH",
        "sla_minutes": 120,
        "sla_label": "≤2 giờ",
        "matchers": [
            ["check ton kho", "lech sl"],
            ["lech so luong", "ton kho"],
            ["bao kho kiem lai"],
            ["ma bi lech sl"],
            ["kiem ton", "lech sl"],
        ],
        "suggested_reply": "Chúng tôi đã ghi nhận các mã đang lệch số lượng tồn và sẽ phối hợp với kho để kiểm tra thực tế, đối chiếu lại số liệu.",
        "handling_plan": "DVKH tổng hợp danh sách mã bị lệch, chuyển Kho kiểm đếm thực tế và đối chiếu lại tồn hệ thống, sau đó cập nhật kết quả xử lý cho người gửi trong vòng 2 giờ.",
    },
    {
        "testcase_id": "TC-29",
        "severity_level": "Cấp 3",
        "lane": "Công nghệ - Sập hệ thống SSC",
        "category": "Công nghệ - Sập hệ thống SSC",
        "priority": "Critical",
        "primary_department": "Công nghệ",
        "assigned_pic": "Bùi Thị Hương + Nguyễn Hoàng Long",
        "notified_departments": ["Công nghệ", "Vận đơn", "Kho", "DVKH", "BLĐ"],
        "market": "PH",
        "sla_minutes": 30,
        "sla_label": "Ngay lập tức / báo BLĐ trong 30 phút",
        "matchers": [["ssc", "khong len don"], ["ssc", "hang tram don", "ket"], ["sap he thong", "ssc"]],
        "suggested_reply": "Chúng tôi đã kích hoạt xử lý khẩn cấp cho sự cố SSC và đang cập nhật ETA khắc phục ngay.",
        "handling_plan": "Notify Công nghệ ngay lập tức, báo BLĐ trong 30 phút, chuyển vận hành sang quy trình thủ công và gửi thông báo rộng tới khách hàng bị ảnh hưởng.",
    },
    {
        "testcase_id": "TC-24",
        "severity_level": "Cấp 3",
        "lane": "Kho - Mất hàng nghiêm trọng",
        "category": "Kho - Lệch tồn hoặc mất hàng nghiêm trọng",
        "priority": "Critical",
        "primary_department": "Kho",
        "assigned_pic": "Lê Phương Dung (MY)",
        "notified_departments": ["DVKH", "Kho", "Kế Toán", "Kinh doanh", "BLĐ"],
        "market": "MY",
        "sla_minutes": 60,
        "sla_label": "Ngay lập tức / báo BLĐ trong 1 giờ",
        "matchers": [["he thong", "con 200", "thuc te kho da het"], ["mat hang", "ton kho", "thuc te het"], ["lech kho", "mat hang"]],
        "suggested_reply": "Chúng tôi đã ghi nhận sự cố lệch tồn nghiêm trọng và đang kiểm đếm, đối soát để báo cáo phương án xử lý khẩn.",
        "handling_plan": "Kho kiểm đếm lại, Kế Toán tính giá trị bồi hoàn, Kinh doanh phối hợp giữ khách và BLĐ nhận báo cáo chi tiết trong 1 giờ.",
    },
    {
        "testcase_id": "TC-25",
        "severity_level": "Cấp 3",
        "lane": "Vận đơn - Claim hàng loạt",
        "category": "Vận đơn - Claim hàng loạt do đơn vị vận chuyển",
        "priority": "Critical",
        "primary_department": "Vận đơn",
        "assigned_pic": "Bùi Thị Hương (Leader VĐ)",
        "notified_departments": ["DVKH", "Vận đơn", "CSR", "Kho", "Kế Toán", "BLĐ"],
        "market": "PH",
        "sla_minutes": 2880,
        "sla_label": "≤T+2",
        "matchers": [["46 don", "j&t", "boi thuong"], ["claim", "hang loat", "j&t"], ["mop meo", "thang 4", "thang 11"]],
        "suggested_reply": "Chúng tôi đã tiếp nhận vụ claim hàng loạt và đang gom hồ sơ, phân loại đơn còn hiệu lực claim để xử lý cùng các bộ phận liên quan.",
        "handling_plan": "Thu danh sách waybill và bằng chứng, phân loại đơn còn hạn claim, phối hợp CSR, Kho, Kế Toán và báo cáo BLĐ phương án chia sẻ rủi ro.",
    },
    {
        "testcase_id": "TC-26",
        "severity_level": "Cấp 3",
        "lane": "Kinh doanh - Nguy cơ rời dịch vụ",
        "category": "Kinh doanh - Khách hàng muốn rời GIP",
        "priority": "Critical",
        "primary_department": "Kinh doanh",
        "assigned_pic": "Hoàng Nguyễn Thanh Tùng (Leader)",
        "notified_departments": ["DVKH", "Kinh doanh", "Kho", "BLĐ"],
        "market": "PH",
        "sla_minutes": 480,
        "sla_label": "Trong ngày",
        "matchers": [["can nhac chuyen sang ben khac"], ["muon roi gip"], ["chat luong dong goi", "anh huong diem san"]],
        "suggested_reply": "Chúng tôi rất tiếc về trải nghiệm này và đang kích hoạt xử lý cấp quản lý để giữ ổn định dịch vụ cho shop.",
        "handling_plan": "Kinh doanh chủ trì phương án giữ khách, Kho kiểm tra quy trình, BLĐ hội ý xử lý và DVKH thiết lập cuộc họp khẩn với khách hàng.",
    },
    {
        "testcase_id": "TC-27",
        "severity_level": "Cấp 3",
        "lane": "Vận đơn - Tỷ lệ hoàn cực cao",
        "category": "Vận đơn - Hiệu suất giao hàng suy giảm nghiêm trọng",
        "priority": "Critical",
        "primary_department": "Vận đơn",
        "assigned_pic": "Bùi Thị Hương (Leader VĐ)",
        "notified_departments": ["DVKH", "Vận đơn", "Telesales", "CSR", "Kinh doanh", "BLĐ"],
        "market": "PH",
        "sla_minutes": 1440,
        "sla_label": "≤T+1",
        "matchers": [["ty le giao thanh cong", "62%"], ["hoan len den 38%"], ["ty le hoan cuc cao"]],
        "suggested_reply": "Chúng tôi đã ghi nhận biến động giao hàng nghiêm trọng và đang mở war-room liên phòng ban để phân tích nguyên nhân và hành động khắc phục.",
        "handling_plan": "Vận đơn, Telesales, CSR, Kinh doanh cùng phân tích nguyên nhân, tổng hợp action plan và gửi báo cáo BLĐ trong T+1.",
    },
    {
        "testcase_id": "TC-28",
        "severity_level": "Cấp 3",
        "lane": "Kho - Hủy hàng hết hạn",
        "category": "Kho - Hàng hết hạn và tranh chấp xử lý",
        "priority": "Critical",
        "primary_department": "Kho",
        "assigned_pic": "Đặng Hồng Khánh (TP Kho)",
        "notified_departments": ["DVKH", "Kho", "Vận đơn", "Kế Toán", "Kinh doanh", "BLĐ"],
        "market": "PH",
        "sla_minutes": 1440,
        "sla_label": "≤T+1",
        "matchers": [["500 san pham", "het han su dung"], ["hang het han", "khong dong y huy"], ["tiep tuc xuat don", "het han"]],
        "suggested_reply": "Chúng tôi đã khóa xử lý khẩn cho lô hàng hết hạn và sẽ phản hồi phương án chính thức sau khi các bộ phận xác nhận theo quy định.",
        "handling_plan": "Dừng xuất hàng ngay, xin ý kiến BLĐ, phối hợp Kế Toán và Vận đơn theo quy trình hủy hàng, DVKH giải thích rõ ràng với khách hàng.",
    },
    {
        "testcase_id": "TC-30",
        "severity_level": "Cấp 3",
        "lane": "Kế Toán - Sai phí nghiêm trọng",
        "category": "Kế Toán - Tranh chấp phí kéo dài",
        "priority": "Critical",
        "primary_department": "Kế Toán",
        "assigned_pic": "Phạm Phương Trà (PH)",
        "notified_departments": ["DVKH", "Kế Toán", "Kinh doanh", "BLĐ"],
        "market": "PH",
        "sla_minutes": 2880,
        "sla_label": "≤T+2",
        "matchers": [["tinh sai phi", "2 thang lien tiep"], ["uph formula", "hoan tien"], ["billing dispute", "hoan tien"]],
        "suggested_reply": "Chúng tôi đã tiếp nhận khiếu nại về phí và đang rà soát lại toàn bộ công thức tính trước khi phản hồi chính thức.",
        "handling_plan": "Kế Toán đối soát lại công thức, Kinh doanh làm việc với khách, BLĐ phê duyệt phương án hoàn phí trước khi cam kết.",
    },
    {
        "testcase_id": "TC-31",
        "severity_level": "Cấp 3",
        "lane": "Kho - Đóng gói sai liên tiếp",
        "category": "Kho - Sai mã sản phẩm lặp lại",
        "priority": "Critical",
        "primary_department": "Kho",
        "assigned_pic": "Đặng Hồng Khánh (TP Kho)",
        "notified_departments": ["DVKH", "Kho", "Kinh doanh", "BLĐ"],
        "market": "PH",
        "sla_minutes": 480,
        "sla_label": "Trong ngày",
        "matchers": [["3 ngay lien tiep", "dong goi sai ma"], ["yeu cau gap truc tiep"], ["dong goi sai", "rat buc xuc"]],
        "suggested_reply": "Chúng tôi xin lỗi vì lỗi đóng gói lặp lại và đang chuyển xử lý ở mức quản lý để khắc phục ngay.",
        "handling_plan": "Kho dừng nguy cơ lặp lỗi, tìm root cause, Kinh doanh gom danh sách mã đơn sai và BLĐ sắp lịch họp với khách trong 24 giờ.",
    },
    {
        "testcase_id": "TC-32",
        "severity_level": "Cấp 3",
        "lane": "Kinh doanh - Pháp lý chậm tiến độ",
        "category": "Pháp lý - Delay giấy tờ mở công ty",
        "priority": "Critical",
        "primary_department": "Kinh doanh",
        "assigned_pic": "Hoàng Nguyễn Thanh Tùng (Leader)",
        "notified_departments": ["DVKH", "Kinh doanh", "BLĐ"],
        "market": "PH",
        "sla_minutes": 480,
        "sla_label": "Trong ngày",
        "matchers": [["giay to mo cong ty", "delay 6 thang"], ["da thanh toan du", "van chua xong"], ["muon gap nguoi co the giai quyet"]],
        "suggested_reply": "Chúng tôi đã tiếp nhận phản ánh pháp lý nghiêm trọng và đang escalate trực tiếp lên cấp quản lý để phản hồi mốc xử lý cụ thể.",
        "handling_plan": "DVKH xin lỗi chuyên nghiệp, không cam kết ngày nếu chưa có xác nhận, Kinh doanh và BLĐ tiếp nhận trực tiếp để đưa ra hạn xử lý trong 24 giờ.",
    },
    {
        "testcase_id": "TC-33",
        "severity_level": "Cấp 3",
        "lane": "Vận đơn - Claim quá hạn",
        "category": "Vận đơn - Claim hỏng vỡ quá hạn",
        "priority": "Critical",
        "primary_department": "Vận đơn",
        "assigned_pic": "Cao Kỳ (TH)",
        "notified_departments": ["DVKH", "Vận đơn", "CSR", "Kế Toán", "BLĐ"],
        "market": "TH",
        "sla_minutes": 4320,
        "sla_label": "≤T+3",
        "matchers": [["20 don", "hong vo", "qua 30 ngay"], ["flash tu choi", "boi thuong"], ["claim qua han", "thailand"]],
        "suggested_reply": "Chúng tôi đã tiếp nhận yêu cầu claim quá hạn và đang rà soát bằng chứng để đề xuất phương án xử lý phù hợp.",
        "handling_plan": "Vận đơn xác nhận hồ sơ đúng chuẩn chưa, CSR và Kế Toán tính mức độ ảnh hưởng, BLĐ quyết định phương án chia sẻ rủi ro.",
    },
    {
        "testcase_id": "TC-11",
        "severity_level": "Cấp 2",
        "lane": "Vận đơn - Delay đơn vị vận chuyển",
        "category": "Vận đơn - Delay giao hàng",
        "priority": "High",
        "primary_department": "Vận đơn",
        "assigned_pic": "Nguyễn Đăng Dương (PH)",
        "notified_departments": ["DVKH", "Vận đơn", "CSR"],
        "market": "PH",
        "sla_minutes": 240,
        "sla_label": "≤4 giờ",
        "matchers": [["j&t", "chua giao"], ["delay", "don", "j&t"], ["pushing", "j&t"]],
        "suggested_reply": "Chúng tôi đã tiếp nhận yêu cầu push đơn hàng và đang phối hợp với vận đơn cùng CSR để cập nhật sớm nhất cho khách mua.",
        "handling_plan": "Thu mã đơn và trạng thái hiện tại, Vận đơn push đơn vị vận chuyển, CSR xử lý khách cuối và phản hồi shop trong 4 giờ.",
    },
    {
        "testcase_id": "TC-12",
        "severity_level": "Cấp 2",
        "lane": "Vận đơn - Hủy đơn gấp",
        "category": "Vận đơn - Hủy đơn khẩn",
        "priority": "High",
        "primary_department": "Vận đơn",
        "assigned_pic": "Cao Kỳ (MY)",
        "notified_departments": ["DVKH", "Vận đơn", "Kho"],
        "market": "MY",
        "sla_minutes": 30,
        "sla_label": "≤30 phút",
        "matchers": [["cancel don", "gap"], ["huy don", "gap ngay bay gio"], ["can cancel", "don"]],
        "suggested_reply": "Chúng tôi đang kiểm tra trạng thái xuất đơn để hỗ trợ hủy khẩn trong thời gian sớm nhất.",
        "handling_plan": "DVKH xác nhận mã đơn và cutoff, Vận đơn xử lý hủy nếu còn kịp, đồng thời báo Kho dừng xuất hàng.",
    },
    {
        "testcase_id": "TC-15",
        "severity_level": "Cấp 2",
        "lane": "Công nghệ - Lỗi đồng bộ SSC",
        "category": "Công nghệ - Lỗi đồng bộ kho",
        "priority": "High",
        "primary_department": "Công nghệ",
        "assigned_pic": "Nguyễn Hoàng Long",
        "notified_departments": ["DVKH", "Công nghệ", "Kho"],
        "market": "PH",
        "sla_minutes": 240,
        "sla_label": "≤4 giờ",
        "matchers": [["ssc", "khong sync kho"], ["kho san bao het hang", "ssc van con"], ["loi ssc", "dong bo kho"]],
        "suggested_reply": "Chúng tôi đã tiếp nhận lỗi đồng bộ SSC và đang phối hợp kỹ thuật để kiểm tra kết nối ngay.",
        "handling_plan": "Thu mã sản phẩm và screenshot, Công nghệ kiểm tra đồng bộ SSC, Kho xác nhận tồn thực tế trong lúc chờ fix.",
    },
    {
        "testcase_id": "TC-22",
        "severity_level": "Cấp 2",
        "lane": "Công nghệ - Đấu nối sàn",
        "category": "Công nghệ - Kết nối shop với SSC",
        "priority": "High",
        "primary_department": "Công nghệ",
        "assigned_pic": "Nguyễn Hoàng Long",
        "notified_departments": ["DVKH", "Công nghệ"],
        "market": "ID",
        "sla_minutes": 480,
        "sla_label": "≤8 giờ",
        "matchers": [["ket noi shop shopee indonesia", "ssc"], ["dau noi san", "ssc"], ["shop id", "ssc"]],
        "suggested_reply": "Chúng tôi đã ghi nhận yêu cầu đấu nối shop vào SSC và sẽ phối hợp kỹ thuật để hoàn tất kết nối.",
        "handling_plan": "DVKH thu Shop ID, Công nghệ thực hiện cấu hình kết nối, khách hàng xác nhận quyền trên shop và test đồng bộ.",
    },
    {
        "testcase_id": "TC-09",
        "severity_level": "Cấp 2",
        "lane": "Kho - Nhập hàng mới",
        "category": "Kho - Nhập hàng về kho chưa lên hệ thống",
        "priority": "High",
        "primary_department": "Kho",
        "assigned_pic": "Vương Quốc Đạt (PH)",
        "notified_departments": ["DVKH", "Kho"],
        "market": "PH",
        "sla_minutes": 120,
        "sla_label": "≤2 giờ",
        "matchers": [["hang ve kho", "chua thay nhap len he thong"], ["nhap hang moi", "he thong"], ["hang ve roi", "chua nhap he thong"]],
        "suggested_reply": "Chúng tôi đang kiểm tra tình trạng nhập kho để cập nhật chính xác thời điểm hàng lên hệ thống.",
        "handling_plan": "DVKH kiểm tra biên bản giao nhận, Kho xác nhận tiến độ nhập và hoàn tất cập nhật hệ thống trong T+1 nếu đã kiểm đủ.",
    },
    {
        "testcase_id": "TC-10",
        "severity_level": "Cấp 2",
        "lane": "Kho - Kế hoạch nhập hàng",
        "category": "Kho - Chuẩn bị nhập hàng mới",
        "priority": "High",
        "primary_department": "Kho",
        "assigned_pic": "Lê Phương Dung (MY)",
        "notified_departments": ["DVKH", "Kho"],
        "market": "MY",
        "sla_minutes": 240,
        "sla_label": "≤4 giờ",
        "matchers": [["tuan sau", "nhap lo hang moi"], ["500 san pham", "chuan bi"], ["ke hoach nhap hang", "malaysia"]],
        "suggested_reply": "Chúng tôi đã nhận yêu cầu chuẩn bị nhập hàng và sẽ gửi đúng biểu mẫu cùng đầu mối kho để phối hợp.",
        "handling_plan": "DVKH gửi biểu mẫu kế hoạch nhập hàng, sau khi khách điền đầy đủ sẽ notify Kho để chuẩn bị tiếp nhận lô hàng.",
    },
    {
        "testcase_id": "TC-14",
        "severity_level": "Cấp 2",
        "lane": "Kho - Hàng hoàn hỏng",
        "category": "Kho - Hàng hoàn về bị hỏng",
        "priority": "High",
        "primary_department": "Kho",
        "assigned_pic": "Lê Phương Dung (ID)",
        "notified_departments": ["DVKH", "Kho", "CSR"],
        "market": "ID",
        "sla_minutes": 1440,
        "sla_label": "≤T+1",
        "matchers": [["hang hoan", "mop meo"], ["chup anh", "video", "hang hoan"], ["indonesia", "hang hoan", "hong"]],
        "suggested_reply": "Chúng tôi đã ghi nhận tình trạng hư hỏng của hàng hoàn và đang yêu cầu kho lập bằng chứng để xử lý claim.",
        "handling_plan": "Kho quay video và chụp ảnh lúc mở kiện, CSR phối hợp xử lý claim với đối tác hoàn hàng và DVKH cập nhật khách theo file chuẩn.",
    },
    {
        "testcase_id": "TC-16",
        "severity_level": "Cấp 2",
        "lane": "Kho - Kiểm kê đột xuất",
        "category": "Kho - Kiểm kê thực tế",
        "priority": "High",
        "primary_department": "Kho",
        "assigned_pic": "Lê Phương Dung (TH)",
        "notified_departments": ["DVKH", "Kho", "Kế Toán"],
        "market": "TH",
        "sla_minutes": 1440,
        "sla_label": "≤T+24h",
        "matchers": [["kiem kho dot xuat"], ["xac nhan so luong thuc te"], ["vitamin c", "thailand", "kiem kho"]],
        "suggested_reply": "Chúng tôi đã tiếp nhận yêu cầu kiểm kê đột xuất và sẽ phối hợp kho cùng kế toán để đối chiếu số lượng thực tế.",
        "handling_plan": "DVKH tạo yêu cầu kiểm kê, Kế Toán lập biên bản và Kho kiểm đếm thực tế để phản hồi trong 24 giờ.",
    },
    {
        "testcase_id": "TC-18",
        "severity_level": "Cấp 2",
        "lane": "Kho - Book xe nội bộ",
        "category": "Kho - Điều phối xe lấy hàng",
        "priority": "High",
        "primary_department": "Kho",
        "assigned_pic": "Vương Quốc Đạt (PH)",
        "notified_departments": ["DVKH", "Kho", "Kế Toán"],
        "market": "PH",
        "sla_minutes": 120,
        "sla_label": "≤2 giờ",
        "matchers": [["book xe", "lay hang"], ["lalamove", "lay hang"], ["lay hang tu kho khac ve kho"]],
        "suggested_reply": "Chúng tôi đang thu thập thông tin để điều phối xe lấy hàng và báo lại chi phí, thời gian xử lý sớm nhất.",
        "handling_plan": "DVKH thu đủ thông tin về hàng và địa điểm, Kho báo giá và đặt xe, Kế Toán theo dõi chi phí phát sinh.",
    },
    {
        "testcase_id": "TC-13",
        "severity_level": "Cấp 2",
        "lane": "Telesales - Tỷ lệ chốt thấp",
        "category": "Telesales - Hiệu suất chốt đơn giảm",
        "priority": "High",
        "primary_department": "Telesales",
        "assigned_pic": "Nguyễn Minh Ngọc (TP)",
        "notified_departments": ["DVKH", "Telesales"],
        "market": "PH",
        "sla_minutes": 360,
        "sla_label": "≤6 giờ",
        "matchers": [["ty le chot", "52%"], ["tuan nay", "thap"], ["ty le chot don thap"]],
        "suggested_reply": "Chúng tôi đang kiểm tra dữ liệu Telesales để phân tích nguyên nhân tỷ lệ chốt đơn giảm và sẽ phản hồi bằng số liệu cụ thể.",
        "handling_plan": "DVKH và Telesales pull báo cáo, phân tích cancel rate, unanswered rate và đưa ra nguyên nhân theo dữ liệu trong 6 giờ.",
    },
    {
        "testcase_id": "TC-19",
        "severity_level": "Cấp 2",
        "lane": "Telesales - Data trùng",
        "category": "Telesales - Chất lượng data đầu vào",
        "priority": "High",
        "primary_department": "Telesales",
        "assigned_pic": "Đặng Thanh Bình (Sale Admin)",
        "notified_departments": ["DVKH", "Telesales"],
        "market": "ALL",
        "sla_minutes": 360,
        "sla_label": "≤6 giờ",
        "matchers": [["data", "trung"], ["30% data", "loc ra"], ["danh trung nhieu"]],
        "suggested_reply": "Chúng tôi đã ghi nhận phản ánh về data trùng và sẽ kiểm tra logic lọc trùng cùng đội Telesales.",
        "handling_plan": "Giải thích nguyên nhân data trùng, Sale Admin rà lại logic lọc và gợi ý phương án tách luồng data để hạn chế chồng chéo.",
    },
    {
        "testcase_id": "TC-17",
        "severity_level": "Cấp 2",
        "lane": "Kế Toán - Chậm đối soát",
        "category": "Kế Toán - Delay file đối soát",
        "priority": "High",
        "primary_department": "Kế Toán",
        "assigned_pic": "Phạm Phương Trà (PH)",
        "notified_departments": ["DVKH", "Kế Toán"],
        "market": "PH",
        "sla_minutes": 240,
        "sla_label": "≤4 giờ",
        "matchers": [["file doi soat", "thu 5"], ["chua thay ve", "doi soat"], ["lich thu 4", "thu 5"]],
        "suggested_reply": "Chúng tôi đang kiểm tra lý do file đối soát chậm và sẽ cập nhật thời gian gửi chính xác trong hôm nay.",
        "handling_plan": "DVKH xác minh nguyên nhân delay, Kế Toán xác nhận ETA gửi file và phản hồi khách trong 4 giờ.",
    },
    {
        "testcase_id": "TC-20",
        "severity_level": "Cấp 2",
        "lane": "Kế Toán - Đổi tài khoản nhận COD",
        "category": "Kế Toán - Thay đổi tài khoản nhận tiền",
        "priority": "High",
        "primary_department": "Kế Toán",
        "assigned_pic": "Kế Toán theo thị trường",
        "notified_departments": ["DVKH", "Kế Toán"],
        "market": "ALL",
        "sla_minutes": 1440,
        "sla_label": "≤T+1",
        "matchers": [["doi tai khoan ngan hang", "nhan tien cod"], ["stk moi", "doi soat"], ["doi stk", "cod"]],
        "suggested_reply": "Chúng tôi đã tiếp nhận yêu cầu đổi tài khoản nhận COD và sẽ hướng dẫn đúng quy trình xác nhận để tránh sai lệch chi trả.",
        "handling_plan": "Hướng dẫn khách gửi thông tin qua email chính thức, Kế Toán xác nhận và cập nhật file tài khoản nhận tiền trong T+1.",
    },
    {
        "testcase_id": "TC-23",
        "severity_level": "Cấp 2",
        "lane": "Kinh doanh - Xác nhận báo giá",
        "category": "Kinh doanh - Thông tin ưu đãi và bảng giá",
        "priority": "High",
        "primary_department": "Kinh doanh",
        "assigned_pic": "Hoàng Nguyễn Thanh Tùng (Leader)",
        "notified_departments": ["DVKH", "Kinh doanh"],
        "market": "MY",
        "sla_minutes": 240,
        "sla_label": "≤4 giờ",
        "matchers": [["uu dai phi ship", "khoi luong"], ["bao gia", "gip malaysia"], ["xac nhan lai thong tin", "phi ship"]],
        "suggested_reply": "Chúng tôi đã tiếp nhận yêu cầu xác nhận báo giá và sẽ để bộ phận Kinh doanh phản hồi chính thức.",
        "handling_plan": "DVKH kết nối khách với PKD, Kinh doanh kiểm tra bảng giá chính xác và phản hồi trong 4 giờ.",
    },
    {
        "testcase_id": "TC-01",
        "severity_level": "Cấp 1",
        "lane": "DVKH - FAQ cutoff",
        "category": "Hỏi đáp quy trình cutoff",
        "priority": "Low",
        "primary_department": "DVKH",
        "assigned_pic": "DVKH",
        "notified_departments": ["DVKH"],
        "market": "ALL",
        "sla_minutes": 5,
        "sla_label": "≤5 phút",
        "matchers": [["cutoff", "malaysia"], ["gio cutoff"], ["cutoff don"]],
        "suggested_reply": "DVKH có thể phản hồi ngay thông tin cutoff theo khung giờ vận hành hiện tại.",
        "handling_plan": "Trả lời trực tiếp khung giờ cutoff tương ứng, không cần notify phòng ban khác.",
    },
    {
        "testcase_id": "TC-02",
        "severity_level": "Cấp 1",
        "lane": "DVKH - Kiểm tra tồn kho",
        "category": "Kiểm tra tồn kho sản phẩm",
        "priority": "Low",
        "primary_department": "DVKH",
        "assigned_pic": "DVKH",
        "notified_departments": ["DVKH"],
        "market": "ALL",
        "sla_minutes": 15,
        "sla_label": "≤15 phút",
        "matchers": [["ton kho"], ["con bao nhieu"], ["stock", "san pham"]],
        "suggested_reply": "Chúng tôi đang kiểm tra tồn kho trên hệ thống để phản hồi số lượng khả dụng sớm nhất.",
        "handling_plan": "DVKH check PM và trả lời số lượng tồn. Nếu cần kiểm kê thực tế thì mới nâng lên Cấp 2 cho Kho.",
    },
    {
        "testcase_id": "TC-03",
        "severity_level": "Cấp 1",
        "lane": "DVKH - Hướng dẫn PM",
        "category": "Hướng dẫn sử dụng phần mềm",
        "priority": "Low",
        "primary_department": "DVKH",
        "assigned_pic": "DVKH",
        "notified_departments": ["DVKH"],
        "market": "ALL",
        "sla_minutes": 5,
        "sla_label": "≤5 phút",
        "matchers": [["lich su nhap kho"], ["phan mem", "xem lich su"], ["xem o dau", "phan mem"]],
        "suggested_reply": "DVKH có thể hướng dẫn thao tác trực tiếp trên phần mềm cho trường hợp này.",
        "handling_plan": "Trả lời đường dẫn thao tác trên hệ thống và gửi ảnh minh họa nếu cần.",
    },
    {
        "testcase_id": "TC-04",
        "severity_level": "Cấp 1",
        "lane": "DVKH - Hướng dẫn hủy đơn",
        "category": "FAQ hủy đơn trên hệ thống",
        "priority": "Low",
        "primary_department": "DVKH",
        "assigned_pic": "DVKH",
        "notified_departments": ["DVKH"],
        "market": "ALL",
        "sla_minutes": 5,
        "sla_label": "≤5 phút",
        "matchers": [["huy don mot loat"], ["huy tung don"], ["co the huy don mot loat"]],
        "suggested_reply": "DVKH có thể trả lời ngay quy định hủy đơn hiện tại trên phần mềm.",
        "handling_plan": "Giải thích phải hủy từng đơn, chỉ escalate nếu khách cần xử lý số lượng lớn hoặc có phát sinh vận hành.",
    },
    {
        "testcase_id": "TC-05",
        "severity_level": "Cấp 1",
        "lane": "DVKH - Kiểm tra trạng thái đơn",
        "category": "Đơn tạo sau cutoff chưa thấy trên hệ thống",
        "priority": "Low",
        "primary_department": "DVKH",
        "assigned_pic": "Lê Quyết Chiến / Nguyễn Khánh Linh",
        "notified_departments": ["DVKH"],
        "market": "PH",
        "sla_minutes": 15,
        "sla_label": "≤15 phút",
        "matchers": [["chua thay tren he thong"], ["tao hom qua 2h chieu"], ["don", "he thong"]],
        "suggested_reply": "Chúng tôi đang kiểm tra trạng thái đơn trên hệ thống và sẽ giải thích ngay nếu vướng cutoff hoặc cần chuyển bộ phận vận đơn.",
        "handling_plan": "DVKH check SSC/Odoo, giải thích rule cutoff. Nếu không tìm thấy đơn thì nâng lên Vận đơn.",
    },
    {
        "testcase_id": "TC-06",
        "severity_level": "Cấp 1",
        "lane": "DVKH - Giải thích đối soát",
        "category": "Giải thích sheet Adjustment",
        "priority": "Low",
        "primary_department": "DVKH",
        "assigned_pic": "DVKH",
        "notified_departments": ["DVKH"],
        "market": "ALL",
        "sla_minutes": 10,
        "sla_label": "≤10 phút",
        "matchers": [["sheet adjustment"], ["doi soat", "dieu chinh"], ["ship 1 thang truoc", "dieu chinh"]],
        "suggested_reply": "DVKH có thể giải thích trực tiếp ý nghĩa của sheet Adjustment và lý do thời gian điều chỉnh có độ trễ.",
        "handling_plan": "Giải thích rõ logic điều chỉnh COD và độ trễ do file từ đơn vị vận chuyển, không cần notify thêm.",
    },
    {
        "testcase_id": "TC-07",
        "severity_level": "Cấp 1",
        "lane": "DVKH - Giới thiệu quy trình telesales",
        "category": "FAQ quy trình Telesales",
        "priority": "Low",
        "primary_department": "DVKH",
        "assigned_pic": "DVKH",
        "notified_departments": ["DVKH"],
        "market": "ALL",
        "sla_minutes": 10,
        "sla_label": "≤10 phút",
        "matchers": [["quy trinh telesale"], ["seller moi", "telesale"], ["hoat dong nhu the nao"]],
        "suggested_reply": "DVKH có thể trả lời ngay quy trình telesales chuẩn cho khách hàng mới.",
        "handling_plan": "Tóm tắt quy trình gọi data, thời điểm lên vận đơn và gửi tài liệu đào tạo nếu cần.",
    },
    {
        "testcase_id": "TC-08",
        "severity_level": "Cấp 1",
        "lane": "DVKH - Hỏi tỷ giá",
        "category": "Tra cứu tỷ giá",
        "priority": "Low",
        "primary_department": "DVKH",
        "assigned_pic": "DVKH",
        "notified_departments": ["DVKH"],
        "market": "PH",
        "sla_minutes": 5,
        "sla_label": "≤5 phút",
        "matchers": [["ty gia peso"], ["peso ve vnd"], ["hom nay ty gia"]],
        "suggested_reply": "DVKH có thể tra cứu và phản hồi ngay tỷ giá cập nhật trong ngày cho khách hàng.",
        "handling_plan": "Check file tỷ giá trong ngày và phản hồi cả tỷ giá chuyển khoản lẫn tiền mặt nếu có.",
    },
    {
        "testcase_id": "TC-21",
        "severity_level": "Cấp 2",
        "lane": "Vận đơn - Đơn giá trị cao",
        "category": "Vận đơn - Phương án xử lý đơn COD giá trị cao",
        "priority": "High",
        "primary_department": "Vận đơn",
        "assigned_pic": "Nguyễn Đăng Dương (PH)",
        "notified_departments": ["DVKH", "Vận đơn", "Kho", "Kế Toán"],
        "market": "PH",
        "sla_minutes": 180,
        "sla_label": "≤3 giờ",
        "matchers": [["26000 peso"], ["51000 peso"], ["don gia tri cao"]],
        "suggested_reply": "Chúng tôi đang kiểm tra phương án vận chuyển phù hợp cho đơn giá trị cao để hạn chế rủi ro phát sinh.",
        "handling_plan": "Tư vấn phương án Lalamove hoặc J&T tách đơn, đồng thời phối hợp Vận đơn, Kho và Kế Toán theo lựa chọn của khách.",
    },
]


def _matches_rule(haystack: str, rule: dict[str, object], detected_market: str) -> int:
    rule_market = rule["market"]
    if rule_market != "ALL" and rule_market != detected_market:
        return 0

    best_score = 0
    for matcher in rule["matchers"]:
        if all(term in haystack for term in matcher):
            score = len(matcher)
            if rule_market != "ALL":
                score += 2
            best_score = max(best_score, score)
    return best_score


def _build_route(rule: dict[str, object], detected_market: str) -> CatalogRoute:
    market = rule["market"] if rule["market"] != "ALL" else detected_market
    return CatalogRoute(
        testcase_id=rule["testcase_id"],
        severity_level=rule["severity_level"],
        lane=rule["lane"],
        category=rule["category"],
        priority=rule["priority"],
        primary_department=rule["primary_department"],
        assigned_pic=rule["assigned_pic"],
        notified_departments=rule["notified_departments"],
        suggested_reply=rule["suggested_reply"],
        handling_plan=rule["handling_plan"],
        market=market,
        sla_minutes=rule["sla_minutes"],
        sla_label=rule["sla_label"],
    )


def route_catalog_request(message_text: str) -> CatalogRoute:
    haystack = normalize_text(message_text)
    detected_market = detect_market(message_text)
    best_rule = None
    best_score = 0

    for rule in CASE_RULES:
        score = _matches_rule(haystack, rule, detected_market)
        if score > best_score:
            best_rule = rule
            best_score = score

    if best_rule is not None:
        return _build_route(best_rule, detected_market)

    return CatalogRoute(
        testcase_id="TC-GENERAL",
        severity_level="Cấp 2",
        lane="DVKH - Chưa phân loại",
        category="Yêu cầu cần DVKH sàng lọc thêm",
        priority="High",
        primary_department="DVKH",
        assigned_pic="DVKH",
        notified_departments=["DVKH"],
        suggested_reply="Chúng tôi đã tiếp nhận yêu cầu và đang rà soát để điều hướng đúng PIC xử lý theo framework DVKH.",
        handling_plan="DVKH cần làm rõ thêm nội dung, đối chiếu framework test hiện hành và điều hướng sang đúng phòng ban nếu phát sinh xử lý liên phòng ban.",
        market=detected_market,
        sla_minutes=720,
        sla_label="≤12 giờ",
    )
